In [11]:
import datetime as dt
import numpy as np
import pandas as pd
import sqlalchemy
import json
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func, inspect
from flask import Flask, jsonify

In [12]:
# Create a database engine using this string format:
# dialect+driver://username:password@host:port/database
# https://docs.sqlalchemy.org/en/14/core/engines.html

##could not get it to work with config file but got it to work this. 
##Have to re-configure later when I can get help.

dialect = 'postgresql'
username = 'postgres'
password = 'bootcamp2021'
host = 'bootcamp-final-cln.ch1wrcuq3max.us-east-2.rds.amazonaws.com'
database = 'crime'
engine = create_engine(f'{dialect}://{username}:{password}@{host}/{database}')

In [13]:
# list all the tables on the AWS RDS
inspector = inspect(engine)
inspector.get_table_names()

['offense_cat_offender_race_2020',
 'offense_cat_offender_sex_2020',
 'offense_cat_type_2020',
 'offense_cat_victim_age_2020',
 'offense_cat_victim_race_2020',
 'offense_cat_victim_sex_2020',
 'state_pop_agencies_2020',
 'gpd_by_state_2020',
 'state_size',
 'property_type_crime',
 'violent_type_crime',
 'offense_cat_loc_2020',
 'offense_cat_state_2020',
 'law_enforcement_state_2020',
 'law_enforcement_state_city_2020',
 'offense_cat_offender_age_2020']

In [14]:
with engine.connect() as conn:
    violent_crime_df = pd.read_sql("SELECT * FROM violent_type_crime", conn)

In [15]:
violent_crime_df.head()

,index,FIPS,crimes,total_law_emp,officers,civilians,percent_edu_less_than_high_school,percent_edu_high_school,percent_edu_some_college,percent_edu_bachelor_or_higher,unemployment_rate,median_HH_Income,population,pop_dens_ppl_per_sqkm,percent_poverty_all_age,percent_poverty_age_0-17,percent_poverty_age_5-17
0,0,1001.0,55.0,69,31,38,11.483395,33.588459,28.356571,26.571573,4.0,58233.0,55200,35.853419,12.1,15.9,14.4
1,1,1003.0,163.0,296,111,185,9.193843,27.659616,31.284081,31.862459,4.2,59871.0,208107,50.541504,10.1,13.5,13.3
2,2,1007.0,3.0,10,9,1,20.942602,44.878773,23.800098,10.378526,4.5,47918.0,22527,13.973114,20.3,25.9,25.2
3,3,1015.0,18.0,56,51,5,15.567326,32.790615,33.160995,18.481064,5.1,47747.0,115098,73.348688,17.2,24.6,22.8
4,4,1033.0,58.0,53,34,19,14.843810,37.834648,29.174259,18.147284,5.4,46683.0,54495,35.496950,14.6,19.4,18.6

In [19]:
result = violent_crime_df.head().to_json(orient="columns")
parsed = json.loads(result)
json.dumps(parsed, indent=4)

'{\n    "index": {\n        "0": 0,\n        "1": 1,\n        "2": 2,\n        "3": 3,\n        "4": 4\n    },\n    "FIPS": {\n        "0": 1001.0,\n        "1": 1003.0,\n        "2": 1007.0,\n        "3": 1015.0,\n        "4": 1033.0\n    },\n    "crimes": {\n        "0": 55.0,\n        "1": 163.0,\n        "2": 3.0,\n        "3": 18.0,\n        "4": 58.0\n    },\n    "total_law_emp": {\n        "0": 69,\n        "1": 296,\n        "2": 10,\n        "3": 56,\n        "4": 53\n    },\n    "officers": {\n        "0": 31,\n        "1": 111,\n        "2": 9,\n        "3": 51,\n        "4": 34\n    },\n    "civilians": {\n        "0": 38,\n        "1": 185,\n        "2": 1,\n        "3": 5,\n        "4": 19\n    },\n    "percent_edu_less_than_high_school": {\n        "0": 11.4833946228,\n        "1": 9.1938428879,\n        "2": 20.9426021576,\n        "3": 15.567325592,\n        "4": 14.8438100815\n    },\n    "percent_edu_high_school": {\n        "0": 33.5884590149,\n        "1": 27.6596164703,\n        "2": 44.8787727356,\n        "3": 32.7906150818,\n        "4": 37.8346481323\n    },\n    "percent_edu_some_college": {\n        "0": 28.3565711975,\n        "1": 31.2840805054,\n        "2": 23.8000984192,\n        "3": 33.1609954834,\n        "4": 29.1742591858\n    },\n    "percent_edu_bachelor_or_higher": {\n        "0": 26.5715732574,\n        "1": 31.8624591827,\n        "2": 10.3785257339,\n        "3": 18.4810638428,\n        "4": 18.1472835541\n    },\n    "unemployment_rate": {\n        "0": 4.0,\n        "1": 4.2,\n        "2": 4.5,\n        "3": 5.1,\n        "4": 5.4\n    },\n    "median_HH_Income": {\n        "0": 58233.0,\n        "1": 59871.0,\n        "2": 47918.0,\n        "3": 47747.0,\n        "4": 46683.0\n    },\n    "population": {\n        "0": 55200,\n        "1": 208107,\n        "2": 22527,\n        "3": 115098,\n        "4": 54495\n    },\n    "pop_dens_ppl_per_sqkm": {\n        "0": 35.85341899,\n        "1": 50.54150356,\n        "2": 13.973114,\n        "3": 73.348688,\n        "4": 35.49694998\n    },\n    "percent_poverty_all_age": {\n        "0": 12.1,\n        "1": 10.1,\n        "2": 20.3,\n        "3": 17.2,\n        "4": 14.6\n    },\n    "percent_poverty_age_0-17": {\n        "0": 15.9,\n        "1": 13.5,\n        "2": 25.9,\n        "3": 24.6,\n        "4": 19.4\n    },\n    "percent_poverty_age_5-17": {\n        "0": 14.4,\n        "1": 13.3,\n        "2": 25.2,\n        "3": 22.8,\n        "4": 18.6\n    }\n}'